version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - sam build --template-file template.yaml --use-container
      - sam package --template-file template.yaml --s3-bucket $BUCKET --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
